### 이슈 등록
POST http://localhost:8080/api/v1/issues
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "summary": "변경할 이슈",
  "description": "변경할 이슈입니다.",
  "type": "TASK",
  "priority": "HIGH",
  "status": "TODO"
}

### 커멘트 등록
POST http://localhost:8080/api/v1/issues/1/comments
Content-Type: application/json

{
  "body": "첫번째 댓글 입니다."
}

### 이슈 조회
GET http://localhost:8080/api/v1/issues/1
Content-Type: application/json

### 이슈 조회
GET http://localhost:8080/api/v1/issues
Content-Type: application/json

### 커멘트 삭제
DELETE http://localhost:8080/api/v1/issues/1/comments/1
Content-Type: application/json


### signup
POST http://localhost:9090/api/v1/users/signup
Content-Type: application/json

{
  "email": "dev@gmail.com",
  "password": "1234",
  "username": "사용자"
}

### signin
POST http://localhost:9090/api/v1/users/signin
Content-Type: application/json

{
  "email":"dev@gmail.com",
  "password": "1234"
}

> {% client.global.set("auth_token", response.body.token); %}


### logout
DELETE http://localhost:9090/api/v1/users/logout
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### me
GET http://localhost:9090/api/v1/users/me
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### username
GET http://localhost:9090/api/v1/users/1/username
Content-Type: application/json
Authorization: Bearer {{auth_token}}


### edit
POST http://localhost:9090/api/v1/users/1
Content-Type: multipart/form-data
Authorization: Bearer {{auth_token}}